### ISSUE TITLE
python payload_dumper_ota.py --diff payload.bin

### ISSUE THREAD

**Issue by sxdqx** [vm03/payload_dumper#1]
python payload_dumper.py --diff payload.bin
Processing devcfg partition....Done
Processing aop partition.......Done
Processing xbl partition...............Done
Processing xbl_config partition...Done
Processing tz partition.........................Done
Processing hyp partition....Done
Processing dsp partition...............................................................Done
Processing keymaster partition.....Done
Processing cmnlib partition...Done
Processing cmnlib64 partition...Done
Processing qupfw partition...Done
Processing bluetooth partition..........................Done
Processing storsec partition...Done
Processing abl partition...Done
Processing modem partition..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Done
Processing custom partition.....................................................................................................Done
Processing vendor partition.........................................................................................................................................................Unsupported type = 9

**Comment by sxdqx** [comment]
python payload_dumper.py --diff payload.bin
Processing devcfg partition....Done
Processing aop partition.......Done
Processing xbl partition...............Done
Processing xbl_config partition...Done
Processing tz partition.........................Done
Processing hyp partition....Done
Processing dsp partition...............................................................Done
Processing keymaster partition.....Done
Processing cmnlib partition...Done
Processing cmnlib64 partition...Done
Processing qupfw partition...Done
Processing bluetooth partition..........................Done
Processing storsec partition...Done
Processing abl partition...Done
Processing modem partition..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Done
Processing custom partition.....................................................................................................Done
Processing vendor partition.........................................................................................................................................................Unsupported type = 9

**Comment by Ku6epMeH** [comment]
Test Script version: 78e70fe.
![Screenshot_2020-01-09-17-17-58-892_ru iiec pydroid3](https://user-images.githubusercontent.com/59539085/72067491-ad622e80-3304-11ea-9b98-44124e6a18f3.png)
![Screenshot_2020-01-09-17-18-05-122_ru iiec pydroid3](https://user-images.githubusercontent.com/59539085/72067494-adfac500-3304-11ea-8973-681f37e72fc6.png)

**Comment by sxdqx** [comment]
Thank you

**Comment by Ku6epMeH** [comment]
> Thank you

Hey. What do you have with the new version of the script, everything works?

**Comment by sxdqx** [comment]
> > Thank you
> 
> Hey. What do you have with the new version of the script, everything works?

Unable to extract partition prompt vendor partition......... Unsupported type = 9

**Comment by vm03** [comment]
Try it https://github.com/vm03/update_payload_extractor
I can't find any other puffdif tools.
