### ISSUE TITLE
Processing vendor partition..................Unsupported type = 9

### ISSUE THREAD

**Issue by sxdqx** [vm03/payload_dumper#14]
Hi, @vm03! :)

Is there a solution to this problem? vendor.img didn't succeed. I have skr-a0

Thanks!

Log:
Processing devcfg partition....Done
Processing aop partition.......Done
Processing xbl partition...............Done
Processing xbl_config partition...Done
Processing tz partition.........................Done
Processing hyp partition....Done
Processing dsp partition...............................................................Done
Processing keymaster partition.....Done
Processing cmnlib partition...Done
Processing cmnlib64 partition...Done
Processing qupfw partition...Done
Processing bluetooth partition..........................Done
Processing storsec partition...Done
Processing abl partition...Done
Processing modem partition.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Done
Processing custom partition.....................................................................................................Done
Processing vendor partition.........................................................................................................................................................Unsupported type = 9

**Comment by vm03** [comment]
No solution now, same 
https://github.com/vm03/payload_dumper/issues/10
