### ISSUE TITLE
Processing aop partition.....Traceback (most recent call last):

### ISSUE THREAD

**Issue by sxdqx** [vm03/payload_dumper#2]
python3 payload_dumper.py --diff payload.bin
Processing devcfg partition....Done
Processing aop partition.....Traceback (most recent call last):
  File "payload_dumper.py", line 157, in <module>
    dump_part(part)
  File "payload_dumper.py", line 109, in dump_part
    data = data_for_op(op,out_file,old_file)
  File "payload_dumper.py", line 89, in data_for_op
    out_file.write('\0' * ext.num_blocks*block_size)
TypeError: 'str' does not support the buffer interface

**Comment by vm03** [comment]
fixed in 78e70fe
