### ISSUE TITLE
  import bsdiff4

### ISSUE THREAD

**Issue by thor9898** [vm03/payload_dumper#29]
im getting this error message:
Traceback (most recent call last):
  File "XXXXXXXXXXXXXX", line 7, in <module>
    import bsdiff4
ModuleNotFoundError: No module named 'bsdiff4'

**Comment by fuckdedeurkruk** [comment]
remove line 7 from payload_dumper.py

**Comment by alibei** [comment]
install bsdiff4 with: pip install bsdiff4
