### ISSUE TITLE
Unsupported type = 10 for differential (delta) payload

### ISSUE THREAD

**Issue by singhnsk** [vm03/payload_dumper#6]
Hi, I tried to merge an incremental OTA with full using the `-diff` function. But I am getting an error:
```
narender@narender-MS-7816:~/Downloads/Payload Dumper/payload_dumper-master$ python3 payload_dumper.py --diff payload.bin
Processing xbl partition.Unsupported type = 10
```
The OTA is from an Android One device and should be complying with however payloads should be created. The full OTA did extract fine for me. Looking for a solution to merge the next incremental OTA to get a full output :)
Any help will be greatly appreciated.

**Comment by vm03** [comment]
try it https://github.com/vm03/update_payload_extractor
