### ISSUE TITLE
error on hyperos rom

### ISSUE THREAD

**Issue by zc57534** [vm03/payload_dumper#65]
hyper rom:miui_CUPID_OS1.0.23.12.4.DEV_8bafbf5abd_14.0

error:Processing system_ext partition............................Traceback (most recent
call last):
  File "payload_dumper.py", line 157, in <module>
    dump_part(part)
  File "payload_dumper.py", line 109, in dump_part
    data = data_for_op(op,out_file,old_file)
  File "payload_dumper.py", line 44, in data_for_op
    data = dec.decompress(data)
_lzma.LZMAError: Input format not supported by decoder

**Comment by vm03** [comment]
double  #64
