### ISSUE TITLE
Author May Be Gone---Can Anyone Update This Program?

### ISSUE THREAD

**Issue by ryanbarillosofficial** [vm03/payload_dumper#69]
It's been 9 months since we've seen updates in this software, and I'm concerned about its future since I use it on every OTA update of my device to patch the init_boot.img to install Magisk.

Given that the the author is in Russia (when you check his profile), possible explanations may explain his time away:
- Moved to different careers
- Internet restrictions/isolation within Russia
- KIA in the war in Ukraine

Which is not good for this project, and thus a best course is to fork & update it. However, given my limited experience with Python, I can't do this task. So I ask anyone else willing to continue this software to keep it going.

**Comment by vm03** [comment]
Hi!
I don't have many time for this project now.
But all PR's are welcome.
And project has 293 forks :)

**Comment by vm03** [comment]
PS: Github force 2FA sucks...
